version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: contract_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: contract_intelligence
    volumes:
      - mongodb_data:/data/db
    networks:
      - contract_network

  # API Backend
  api:
    build: .
    container_name: contract_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - contract_network

volumes:
  mongodb_data:

networks:
  contract_network:
    driver: bridge
